In [25]:
import pandas as pd

ground = pd.read_csv('Monk_glucose_iML515.csv')
ground.head(10)

,Unnamed: 0,Gene,Prediction,Measured_growth,Growth_cutoff,Computational_growth,Condition,Dataset
0,22114,b0002,FP,"0,013333333","0,5","0,8217979336",Glucose,Monk 2015
1,22115,b0003,TN,0,"0,5",0,Glucose,Monk 2015
2,22116,b0004,TN,0,"0,5",0,Glucose,Monk 2015
3,22117,b0007,TP,"1,073333333","0,5","0,8217979336",Glucose,Monk 2015
4,22118,b0008,TP,"0,985","0,5","0,8217979336",Glucose,Monk 2015
5,22119,b0009,TP,"1,043333333","0,5","0,8217979336",Glucose,Monk 2015
6,22120,b0010,TP,"0,966666667","0,5","0,8043091833",Glucose,Monk 2015
7,22121,b0019,TP,"0,936666667","0,5","0,8217979336",Glucose,Monk 2015
8,22122,b0025,TN,0,"0,5",0,Glucose,LB_essential
9,22123,b0029,TN,0,"0,5",0,Glucose,LB_essential

A continuació, seleccionam els Falsos Positius i els Vertaders Negatius, que són aquells que, són essencials en els estudis de Monk et. al.

In [22]:
essentials = ground[(ground["Prediction"] == "FP")| (ground["Prediction"] == "TN")]
essentials.to_csv("essentials.csv", index=False)
essentials

,Unnamed: 0,Gene,Prediction,Measured_growth,Growth_cutoff,Computational_growth,Condition,Dataset
0,22114,b0002,FP,"0,013333333","0,5","0,8217979336",Glucose,Monk 2015
1,22115,b0003,TN,0,"0,5",0,Glucose,Monk 2015
2,22116,b0004,TN,0,"0,5",0,Glucose,Monk 2015
8,22122,b0025,TN,0,"0,5",0,Glucose,LB_essential
9,22123,b0029,TN,0,"0,5",0,Glucose,LB_essential
...,...,...,...,...,...,...,...,...
1453,23567,b4245,TN,"0,266666667","0,5",0,Glucose,Monk 2015
1455,23569,b4261,TN,0,"0,5",0,Glucose,LB_essential
1456,23570,b4262,TN,0,"0,5",0,Glucose,LB_essential
1484,23598,b4388,FP,0,"0,5","0,7876193944",Glucose,Monk 2015
1488,23602,b4407,TN,"0,316666667","0,5",0,Glucose,Monk 2015

In [20]:
ground["Measured_growth"] = pd.to_numeric(ground["Measured_growth"], errors="coerce")
#essentials = ground[(ground["Measured_growth"] <= 0.5)]

In [24]:
estranys = essentials[essentials['Measured_growth'] <= 0.5]
estranys

TypeError: '<=' not supported between instances of 'str' and 'float'

In [28]:
data2 = pd.read_csv("Escherichia_coli_K12_genes.csv")
data2 = data2[data2['dataset'] == 173]

In [30]:
data2_ess = data2[data2['essentiality'] == 'E']

In [32]:
data2_ess.to_csv("data2_ess", index=False)